const express = require('express');
const app = express();
const port = 3000;
const path = require('path');

app.route('/').get((req, res) => {
	/* Where it says "/routes/index.html", make sure it points to where
       you put the html file generated by ChatGPT*/
	res.sendFile(path.join(__dirname + '/routes/index.html'));
});

app.listen(port, (error) => {
	if (error) {
		return console.log(`Server failed to start: ${error}.`);
	}
	console.log(`Server now accessible at http://localhost:${port}`);
});
