//Imports
const express = require('express');
const app = express();
const port = 3000;
const path = require('path');
const mongoose = require('mongoose');
const dotenv = require('dotenv');

//Mongoose setup
main().catch((err) => console.log(err));

async function main() {
	//Make sure that where I wrote "orders" you write whatever you want the name of the database you are storing to be.
	const process = dotenv.config().parsed;
	const connString = process.CONNECTION_STRING;
	await mongoose.connect(connString);
}

//Routing for main HTML page
app.use(express.json());

app.route('/').get((req, res) => {
	/* Where it says "/static/index.html", make sure it points to where
       you put the html file generated by ChatGPT*/
	res.sendFile(path.join(__dirname + '/static/index.html'));
});

//Routing for Orders API
const ordersRouter = require('./routes/orders.js');
app.use('/orders', ordersRouter);

//App setup
app.listen(port, (error) => {
	if (error) {
		return console.log(`Server failed to start: ${error}.`);
	}
	console.log(`Server now accessible at http://localhost:${port}`);
});
